version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement

  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - enhancement

  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/setup-dprint"
      - "/.github/actions/setup-node"
      - "/.github/actions/setup-rust"
    schedule:
      interval: weekly
    labels:
      - enhancement
