pub const TEST_DATABASE_URL_ENV: &str = "SQLAY_TEST_DATABASE_URL";

pub const UNUSED_DATABASE_URL: &str = "mysql://sqlay:sqlay@127.0.0.1:3306/sqlay";

pub const DUPLICATE_IDS_FIXTURE: &str =
    include_str!("../../fixtures/sql/invalid/duplicate_ids.sql");

pub const EXEC_CARDINALITY_FIXTURE: &str =
    include_str!("../../fixtures/sql/invalid/exec_cardinality.sql");

pub const VALID_CONFIG: &str = r#"
{
  "source": {
    "include": ["sql/**/*.sql"]
  },
  "output": {
    "dir": "src/generated/sqlay"
  },
  "database": {
    "dialect": "mysql",
    "urlEnv": "SQLAY_TEST_DATABASE_URL"
  },
  "target": {
    "language": "typescript"
  }
}
"#;

pub const UNSUPPORTED_CONFIG: &str = r#"
{
  "source": {
    "include": ["sql/**/*.sql"]
  },
  "output": {
    "dir": "src/generated/sqlay"
  },
  "database": {
    "dialect": "postgres",
    "urlEnv": "DATABASE_URL"
  },
  "target": {
    "language": "go"
  }
}
"#;

pub const INVALID_SOURCE_CONFIG: &str = r#"
{
  "source": {
    "include": ["invalid/**/*.sql"]
  },
  "output": {
    "dir": "generated-invalid"
  },
  "database": {
    "dialect": "mysql",
    "urlEnv": "SQLAY_TEST_DATABASE_URL"
  },
  "target": {
    "language": "typescript"
  }
}
"#;

pub const FRAGMENT_ONLY_SQL: &str = r"
/* @sqlay
{
  type: fragment
  id: activeOnly
}
*/
AND u.active = 1
";

pub const NESTED_CONFIG_WITH_PARENT_INCLUDE: &str = r#"
{
  "source": {
    "include": ["../sql/**/*.sql"]
  },
  "output": {
    "dir": "generated"
  },
  "database": {
    "dialect": "mysql",
    "urlEnv": "SQLAY_TEST_DATABASE_URL"
  },
  "target": {
    "language": "typescript"
  }
}
"#;

pub fn unique_temp_dir(prefix: &str) -> std::path::PathBuf {
    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("system time should be after Unix epoch")
        .as_nanos();
    let thread_id = std::thread::current().id();

    std::env::temp_dir().join(format!(
        "{prefix}-{}-{thread_id:?}-{unique}",
        std::process::id()
    ))
}

/// Writes a config plus one fragment-only SQL source and returns the output SQL dir.
pub fn write_fragment_only_project(config_dir: &std::path::Path) -> std::path::PathBuf {
    let sql_dir = config_dir.join("sql");
    let output_dir = config_dir.join("src/generated/sqlay/sql");
    std::fs::create_dir_all(&sql_dir).expect("temp SQL dir should be created");
    std::fs::create_dir_all(&output_dir).expect("temp output dir should be created");
    std::fs::write(config_dir.join("sqlay.config.json"), VALID_CONFIG)
        .expect("temp config should be written");
    std::fs::write(sql_dir.join("fragments.sql"), FRAGMENT_ONLY_SQL)
        .expect("fragment-only SQL should be written");

    output_dir
}

/// Writes a managed generated file fixture that clean can classify as stale.
pub fn write_managed_generated_file(path: &std::path::Path) {
    std::fs::write(path, "// @generated by sqlay. Do not edit.\nexport {}\n")
        .expect("stale generated fragment output should be written");
}
