//! Filesystem generated-output adapter.

use std::fs;
use std::path::Path;

use sqlcomp_app::GeneratedFileWriter;
use sqlcomp_core as core;

/// Filesystem-backed generated file writer.
#[derive(Clone, Copy, Debug, Default)]
pub struct FileSystemGeneratedFileWriter;

impl GeneratedFileWriter for FileSystemGeneratedFileWriter {
    fn write(&self, files: &core::GeneratedFiles) -> core::DiagnosticResult<()> {
        for file in files.files() {
            write_generated_file(file)?;
        }

        Ok(())
    }
}

fn write_generated_file(file: &core::GeneratedFile) -> core::DiagnosticResult<()> {
    if let Some(parent) = file
        .path()
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).map_err(|error| {
            file_error(
                format!(
                    "failed to create generated output directory `{}`: {error}",
                    parent.display()
                ),
                parent,
            )
        })?;
    }

    fs::write(file.path(), file.contents()).map_err(|error| {
        file_error(
            format!(
                "failed to write generated file `{}`: {error}",
                file.path().display()
            ),
            file.path(),
        )
    })
}

fn file_error(message: impl Into<String>, path: &Path) -> core::DiagnosticReport {
    core::DiagnosticReport::new(
        core::Diagnostic::error(message).with_location(core::SourceLocation::for_path(path)),
    )
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;

    use super::FileSystemGeneratedFileWriter;
    use sqlcomp_app::GeneratedFileWriter;
    use sqlcomp_core as core;

    #[test]
    fn writes_generated_files_and_creates_parent_directories() {
        let output_dir = unique_temp_dir("write-parents");
        let file_path = output_dir.join("sql").join("admin").join("users.ts");
        let files = core::GeneratedFiles::new(vec![core::GeneratedFile::new(
            file_path.clone(),
            "// @generated by sqlcomp. Do not edit.\n".to_owned(),
        )]);

        FileSystemGeneratedFileWriter
            .write(&files)
            .expect("writer should create parent directories and write file");

        assert_eq!(
            fs::read_to_string(&file_path).expect("generated file should be readable"),
            "// @generated by sqlcomp. Do not edit.\n"
        );

        fs::remove_dir_all(output_dir).expect("temp output dir should be removed");
    }

    #[test]
    fn overwrites_existing_same_path_files() {
        let output_dir = unique_temp_dir("overwrite");
        let file_path = output_dir.join("sql").join("users.ts");
        fs::create_dir_all(file_path.parent().expect("file path should have a parent"))
            .expect("temp parent directory should be created");
        fs::write(&file_path, "keep me").expect("existing file should be written");
        let files = core::GeneratedFiles::new(vec![core::GeneratedFile::new(
            file_path.clone(),
            "// @generated by sqlcomp. Do not edit.\nexport {}\n".to_owned(),
        )]);

        FileSystemGeneratedFileWriter
            .write(&files)
            .expect("writer should overwrite generated output path");

        assert_eq!(
            fs::read_to_string(&file_path).expect("generated file should be readable"),
            "// @generated by sqlcomp. Do not edit.\nexport {}\n"
        );

        fs::remove_dir_all(output_dir).expect("temp output dir should be removed");
    }

    fn unique_temp_dir(name: &str) -> PathBuf {
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system time should be after Unix epoch")
            .as_nanos();

        std::env::temp_dir().join(format!(
            "sqlcomp-output-fs-{name}-{}-{unique}",
            std::process::id()
        ))
    }
}
