//! TypeScript target generation adapter.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use sqlcomp_app::TargetGenerator;
use sqlcomp_core as core;

const GENERATED_FILE_HEADER: &str = "// @generated by sqlcomp. Do not edit.\n\n";

/// TypeScript symbols generated from one compiled query ID.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct QuerySymbols {
    function: String,
    input_type: String,
    row_type: String,
    output_type: String,
}

impl QuerySymbols {
    /// Build TypeScript symbol names for a compiled query.
    #[must_use]
    pub fn for_query(query: &core::CompiledQuery) -> Self {
        Self::from_query_id(query.id().as_str())
    }

    /// Build TypeScript symbol names from a validated query ID.
    #[must_use]
    pub fn from_query_id(query_id: &str) -> Self {
        Self {
            function: query_id.to_owned(),
            input_type: format!("{query_id}_Input"),
            row_type: format!("{query_id}_Row"),
            output_type: format!("{query_id}_Output"),
        }
    }

    /// Generated query builder function name.
    #[must_use]
    pub fn function_name(&self) -> &str {
        &self.function
    }

    /// Generated input type alias name.
    #[must_use]
    pub fn input_type_name(&self) -> &str {
        &self.input_type
    }

    /// Generated result row type alias name.
    #[must_use]
    pub fn row_type_name(&self) -> &str {
        &self.row_type
    }

    /// Generated output type alias name.
    #[must_use]
    pub fn output_type_name(&self) -> &str {
        &self.output_type
    }
}

/// Render text as a TypeScript double-quoted string literal.
#[must_use]
pub fn typescript_string_literal(value: &str) -> String {
    let mut literal = String::with_capacity(value.len() + 2);
    literal.push('"');

    for ch in value.chars() {
        match ch {
            '"' => literal.push_str("\\\""),
            '\\' => literal.push_str("\\\\"),
            '\n' => literal.push_str("\\n"),
            '\r' => literal.push_str("\\r"),
            '\t' => literal.push_str("\\t"),
            '\u{0008}' => literal.push_str("\\b"),
            '\u{000c}' => literal.push_str("\\f"),
            '\u{2028}' => literal.push_str("\\u2028"),
            '\u{2029}' => literal.push_str("\\u2029"),
            control if control.is_control() => {
                let code_point = u32::from(control);
                write!(&mut literal, "\\u{code_point:04X}").expect("writing to String cannot fail");
            }
            other => literal.push(other),
        }
    }

    literal.push('"');
    literal
}

/// Render a generated query builder `sql` property.
#[must_use]
pub fn render_sql_property(query: &core::CompiledQuery) -> String {
    format!("    sql: {},", typescript_string_literal(query.sql()))
}

/// Render a full generated TypeScript file from compiled queries.
#[must_use]
pub fn render_generated_file_contents(queries: &[core::CompiledQuery]) -> String {
    render_generated_file_contents_from_iter(queries.iter())
}

fn render_generated_file_contents_from_iter<'a>(
    queries: impl IntoIterator<Item = &'a core::CompiledQuery>,
) -> String {
    let mut contents = String::from(GENERATED_FILE_HEADER);
    let mut is_first_query = true;

    for query in queries {
        if is_first_query {
            is_first_query = false;
        } else {
            contents.push('\n');
        }
        contents.push_str(&render_query(query));
    }

    contents
}

/// Render TypeScript declarations and the SQL builder for one compiled query.
#[must_use]
pub fn render_query(query: &core::CompiledQuery) -> String {
    let symbols = QuerySymbols::for_query(query);
    let mut output = String::new();

    writeln!(
        &mut output,
        "export type {} = Record<string, never>;",
        symbols.input_type_name()
    )
    .expect("writing to String cannot fail");
    output.push('\n');

    writeln!(&mut output, "export type {} = {{", symbols.row_type_name())
        .expect("writing to String cannot fail");
    for column in query.row() {
        writeln!(
            &mut output,
            "  {}: {};",
            typescript_property_name(column.name()),
            typescript_result_type(column)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("};\n\n");

    writeln!(
        &mut output,
        "export type {} = {};",
        symbols.output_type_name(),
        typescript_output_type(&symbols, query.cardinality())
    )
    .expect("writing to String cannot fail");
    output.push('\n');

    writeln!(&mut output, "export function {}(", symbols.function_name())
        .expect("writing to String cannot fail");
    writeln!(
        &mut output,
        "  _input: {} = {{}},",
        symbols.input_type_name()
    )
    .expect("writing to String cannot fail");
    output.push_str("): { sql: string; params: readonly [] } {\n");
    output.push_str("  return {\n");
    writeln!(&mut output, "{}", render_sql_property(query)).expect("writing to String cannot fail");
    output.push_str("    params: [] as const,\n");
    output.push_str("  };\n");
    output.push_str("}\n");

    output
}

fn typescript_output_type(symbols: &QuerySymbols, cardinality: core::Cardinality) -> String {
    let row_type = symbols.row_type_name();

    match cardinality {
        core::Cardinality::One => format!("{row_type} | null"),
        core::Cardinality::Many => format!("{row_type}[]"),
    }
}

fn typescript_result_type(column: &core::ResultColumn) -> String {
    let base_type = typescript_core_type(column.ty());

    if column.is_nullable() {
        format!("{base_type} | null")
    } else {
        base_type.to_owned()
    }
}

const fn typescript_core_type(ty: core::CoreType) -> &'static str {
    match ty {
        core::CoreType::Bool => "boolean",
        core::CoreType::Int32 | core::CoreType::Float64 => "number",
        core::CoreType::Int64
        | core::CoreType::Decimal
        | core::CoreType::Date
        | core::CoreType::Time
        | core::CoreType::DateTime
        | core::CoreType::String => "string",
        core::CoreType::Bytes => "Uint8Array",
        core::CoreType::Json | core::CoreType::Unknown => "unknown",
    }
}

fn typescript_property_name(name: &str) -> String {
    if is_simple_typescript_identifier(name) {
        name.to_owned()
    } else {
        typescript_string_literal(name)
    }
}

fn is_simple_typescript_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    is_identifier_start(first) && chars.all(is_identifier_continue)
}

const fn is_identifier_start(ch: char) -> bool {
    ch == '_' || ch == '$' || ch.is_ascii_alphabetic()
}

const fn is_identifier_continue(ch: char) -> bool {
    is_identifier_start(ch) || ch.is_ascii_digit()
}

/// Dummy TypeScript target generator.
#[derive(Clone, Copy, Debug, Default)]
pub struct TypeScriptTargetGenerator;

impl TargetGenerator for TypeScriptTargetGenerator {
    fn generate(
        &self,
        plan: &core::CompilationPlan,
        queries: &[core::CompiledQuery],
    ) -> core::DiagnosticResult<core::GeneratedFiles> {
        let mut queries_by_source_path: BTreeMap<PathBuf, Vec<&core::CompiledQuery>> =
            BTreeMap::new();

        for query in queries {
            let source_path = query_source_path(query)?;
            queries_by_source_path
                .entry(source_path.to_path_buf())
                .or_default()
                .push(query);
        }

        let mut files = Vec::with_capacity(queries_by_source_path.len());
        for (source_path, source_queries) in queries_by_source_path {
            let output_path = generated_typescript_path(plan.output_dir(), &source_path);
            let contents = render_generated_file_contents_from_iter(source_queries);
            files.push(core::GeneratedFile::new(output_path, contents));
        }

        Ok(core::GeneratedFiles::new(files))
    }
}

fn query_source_path(query: &core::CompiledQuery) -> core::DiagnosticResult<&Path> {
    let Some(source_path) = query.source_path() else {
        return Err(core::DiagnosticReport::new(core::Diagnostic::error(
            format!(
                "compiled query `{}` does not include a source file path for output mapping",
                query.id().as_str()
            ),
        )));
    };

    if !is_safe_relative_path(source_path) {
        return Err(core::DiagnosticReport::new(core::Diagnostic::error(
            format!(
                "compiled query `{}` has invalid source file path `{}`; expected a config-relative SQL path",
                query.id().as_str(),
                source_path.display()
            ),
        )));
    }

    Ok(source_path)
}

fn generated_typescript_path(output_dir: &Path, source_relative_path: &Path) -> PathBuf {
    output_dir.join(source_relative_path).with_extension("ts")
}

fn is_safe_relative_path(path: &Path) -> bool {
    path.file_name().is_some()
        && path
            .components()
            .all(|component| matches!(component, Component::CurDir | Component::Normal(_)))
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use super::{
        QuerySymbols, TypeScriptTargetGenerator, render_generated_file_contents, render_query,
        render_sql_property, typescript_string_literal,
    };
    use sqlcomp_app::TargetGenerator;
    use sqlcomp_core as core;

    #[test]
    fn query_symbols_use_id_exactly_with_fixed_suffixes() {
        for query_id in ["listUsers", "list_users", "_findUser2", "HTTPStatus200"] {
            let symbols = QuerySymbols::from_query_id(query_id);

            assert_eq!(symbols.function_name(), query_id);
            assert_eq!(symbols.input_type_name(), format!("{query_id}_Input"));
            assert_eq!(symbols.row_type_name(), format!("{query_id}_Row"));
            assert_eq!(symbols.output_type_name(), format!("{query_id}_Output"));
        }
    }

    #[test]
    fn query_symbols_are_derived_from_compiled_query_id_without_transformation() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("list_users".to_owned()),
            "SELECT id FROM users;".to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            Vec::new(),
        );

        let symbols = QuerySymbols::for_query(&query);

        assert_eq!(symbols.function_name(), "list_users");
        assert_eq!(symbols.input_type_name(), "list_users_Input");
        assert_eq!(symbols.row_type_name(), "list_users_Row");
        assert_eq!(symbols.output_type_name(), "list_users_Output");
    }

    #[test]
    fn sql_literal_uses_double_quotes_for_template_literal_hazards() {
        let sql = "SELECT `id`, '${literal}' FROM `users` WHERE note = '${not_param}';";

        assert_eq!(
            typescript_string_literal(sql),
            r#""SELECT `id`, '${literal}' FROM `users` WHERE note = '${not_param}';""#
        );
    }

    #[test]
    fn sql_literal_escapes_quotes_backslashes_and_line_breaks() {
        let sql = "SELECT \"quoted\", 'single', C:\\tmp\\users\nFROM users\r\nWHERE tab = '\t';";

        assert_eq!(
            typescript_string_literal(sql),
            r#""SELECT \"quoted\", 'single', C:\\tmp\\users\nFROM users\r\nWHERE tab = '\t';""#
        );
    }

    #[test]
    fn sql_literal_escapes_javascript_line_separators_and_other_controls() {
        let sql = "SELECT '\u{0001}\u{2028}\u{2029}';";

        assert_eq!(
            typescript_string_literal(sql),
            r#""SELECT '\u0001\u2028\u2029';""#
        );
    }

    #[test]
    fn rendered_sql_property_uses_safe_literal() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("findNotes".to_owned()),
            "SELECT `body`, '${not_param}'\nFROM notes;".to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            Vec::new(),
        );

        assert_eq!(
            render_sql_property(&query),
            r#"    sql: "SELECT `body`, '${not_param}'\nFROM notes;","#
        );
    }

    #[test]
    fn renders_input_row_output_types_and_builder_for_many_cardinality() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("listUsers".to_owned()),
            "SELECT id, name FROM users;".to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            vec![
                core::ResultColumn::new("id".to_owned(), core::CoreType::Int32, false),
                core::ResultColumn::new("name".to_owned(), core::CoreType::String, true),
            ],
        );

        assert_eq!(
            render_query(&query),
            r#"export type listUsers_Input = Record<string, never>;

export type listUsers_Row = {
  id: number;
  name: string | null;
};

export type listUsers_Output = listUsers_Row[];

export function listUsers(
  _input: listUsers_Input = {},
): { sql: string; params: readonly [] } {
  return {
    sql: "SELECT id, name FROM users;",
    params: [] as const,
  };
}
"#
        );
    }

    #[test]
    fn renders_one_cardinality_output_as_row_or_null() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("findLatestUser".to_owned()),
            "SELECT id FROM users ORDER BY id DESC LIMIT 1;".to_owned(),
            core::Cardinality::One,
            Vec::new(),
            vec![core::ResultColumn::new(
                "id".to_owned(),
                core::CoreType::Int64,
                false,
            )],
        );

        assert!(
            render_query(&query)
                .contains("export type findLatestUser_Output = findLatestUser_Row | null;")
        );
    }

    #[test]
    fn renders_precision_sensitive_and_unknown_types_conservatively() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("inspectTypes".to_owned()),
            "SELECT * FROM fixture_types;".to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            vec![
                core::ResultColumn::new("active".to_owned(), core::CoreType::Bool, false),
                core::ResultColumn::new("smallCount".to_owned(), core::CoreType::Int32, false),
                core::ResultColumn::new("largeCount".to_owned(), core::CoreType::Int64, false),
                core::ResultColumn::new("ratio".to_owned(), core::CoreType::Float64, false),
                core::ResultColumn::new("amount".to_owned(), core::CoreType::Decimal, false),
                core::ResultColumn::new("payload".to_owned(), core::CoreType::Bytes, false),
                core::ResultColumn::new("birthDate".to_owned(), core::CoreType::Date, false),
                core::ResultColumn::new("deliveryWindow".to_owned(), core::CoreType::Time, false),
                core::ResultColumn::new("createdAt".to_owned(), core::CoreType::DateTime, false),
                core::ResultColumn::new("settings".to_owned(), core::CoreType::Json, true),
                core::ResultColumn::new("shape".to_owned(), core::CoreType::Unknown, true),
            ],
        );

        assert_eq!(
            render_query(&query),
            r#"export type inspectTypes_Input = Record<string, never>;

export type inspectTypes_Row = {
  active: boolean;
  smallCount: number;
  largeCount: string;
  ratio: number;
  amount: string;
  payload: Uint8Array;
  birthDate: string;
  deliveryWindow: string;
  createdAt: string;
  settings: unknown | null;
  shape: unknown | null;
};

export type inspectTypes_Output = inspectTypes_Row[];

export function inspectTypes(
  _input: inspectTypes_Input = {},
): { sql: string; params: readonly [] } {
  return {
    sql: "SELECT * FROM fixture_types;",
    params: [] as const,
  };
}
"#
        );
    }

    #[test]
    fn renders_result_column_names_as_typescript_property_names_without_transforming() {
        let query = core::CompiledQuery::new(
            core::QueryId::new("selectOddColumns".to_owned()),
            "SELECT 1 AS `user id`, 2 AS `class`;".to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            vec![
                core::ResultColumn::new("user id".to_owned(), core::CoreType::Int32, false),
                core::ResultColumn::new("class".to_owned(), core::CoreType::String, false),
            ],
        );

        assert!(render_query(&query).contains("  \"user id\": number;\n  class: string;"));
    }

    #[test]
    fn renders_generated_file_header_and_multiple_queries() {
        let queries = [
            core::CompiledQuery::new(
                core::QueryId::new("listUsers".to_owned()),
                "SELECT id FROM users;".to_owned(),
                core::Cardinality::Many,
                Vec::new(),
                vec![core::ResultColumn::new(
                    "id".to_owned(),
                    core::CoreType::Int32,
                    false,
                )],
            ),
            core::CompiledQuery::new(
                core::QueryId::new("findLatestUser".to_owned()),
                "SELECT id FROM users LIMIT 1;".to_owned(),
                core::Cardinality::One,
                Vec::new(),
                vec![core::ResultColumn::new(
                    "id".to_owned(),
                    core::CoreType::Int32,
                    false,
                )],
            ),
        ];

        let contents = render_generated_file_contents(&queries);

        assert!(contents.starts_with("// @generated by sqlcomp. Do not edit.\n\n"));
        assert!(contents.contains("export type listUsers_Output = listUsers_Row[];"));
        assert!(
            contents.contains("export type findLatestUser_Output = findLatestUser_Row | null;")
        );
    }

    #[test]
    fn generator_maps_nested_sql_paths_under_output_dir() {
        let plan = compilation_plan();
        let query = compiled_query("listAdmins", "SELECT id FROM admins;")
            .with_source_path("sql/admin/users.sql");

        let files = TypeScriptTargetGenerator
            .generate(&plan, &[query])
            .expect("generator should map SQL source path to TypeScript output path");

        assert_eq!(files.files().len(), 1);
        assert_eq!(
            files.files()[0].path(),
            Path::new("/tmp/sqlcomp-project/src/generated/sqlcomp/sql/admin/users.ts")
        );
        assert!(
            files.files()[0]
                .contents()
                .contains("export function listAdmins(")
        );
    }

    #[test]
    fn generator_combines_queries_from_same_sql_file_into_one_module() {
        let plan = compilation_plan();
        let queries = [
            compiled_query("listUsers", "SELECT id FROM users;").with_source_path("sql/users.sql"),
            compiled_query("findLatestUser", "SELECT id FROM users LIMIT 1;")
                .with_source_path("sql/users.sql"),
            compiled_query("listRoles", "SELECT id FROM roles;")
                .with_source_path("sql/admin/roles.sql"),
        ];

        let files = TypeScriptTargetGenerator
            .generate(&plan, &queries)
            .expect("generator should group queries by source SQL file");

        assert_eq!(files.files().len(), 2);
        let users_contents = file_contents(
            &files,
            Path::new("/tmp/sqlcomp-project/src/generated/sqlcomp/sql/users.ts"),
        );
        assert!(users_contents.contains("export function listUsers("));
        assert!(users_contents.contains("export function findLatestUser("));
        assert!(!users_contents.contains("export function listRoles("));
    }

    fn compilation_plan() -> core::CompilationPlan {
        core::CompilationPlan::new(
            PathBuf::from("/tmp/sqlcomp-project"),
            vec![PathBuf::from("/tmp/sqlcomp-project/sql/**/*.sql")],
            Vec::new(),
            PathBuf::from("/tmp/sqlcomp-project/src/generated/sqlcomp"),
            core::DatabaseConfig::new(core::DatabaseDialect::MySql, "DATABASE_URL".to_owned()),
            core::TargetConfig::new(core::TargetLanguage::TypeScript),
        )
    }

    fn compiled_query(id: &str, sql: &str) -> core::CompiledQuery {
        core::CompiledQuery::new(
            core::QueryId::new(id.to_owned()),
            sql.to_owned(),
            core::Cardinality::Many,
            Vec::new(),
            vec![core::ResultColumn::new(
                "id".to_owned(),
                core::CoreType::Int32,
                false,
            )],
        )
    }

    fn file_contents<'a>(files: &'a core::GeneratedFiles, path: &Path) -> &'a str {
        files
            .files()
            .iter()
            .find(|file| file.path() == path)
            .unwrap_or_else(|| panic!("expected generated file `{}`", path.display()))
            .contents()
    }
}
