use std::path::{Path, PathBuf};

/// Header line that identifies files generated and managed by sqlay.
pub const GENERATED_FILE_HEADER: &str = "// @generated by sqlay. Do not edit.";

/// Generated target-language file set.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFiles {
    files: Vec<GeneratedFile>,
}

impl GeneratedFiles {
    /// Build generated files.
    #[must_use]
    pub const fn new(files: Vec<GeneratedFile>) -> Self {
        Self { files }
    }

    /// Files produced by a target generator.
    #[must_use]
    pub fn files(&self) -> &[GeneratedFile] {
        &self.files
    }
}

/// One generated target-language file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    path: PathBuf,
    contents: String,
}

impl GeneratedFile {
    /// Build a generated file.
    #[must_use]
    pub const fn new(path: PathBuf, contents: String) -> Self {
        Self { path, contents }
    }

    /// Generated file path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Generated file contents.
    #[must_use]
    pub fn contents(&self) -> &str {
        &self.contents
    }
}
