//! Inner domain types and language-neutral IR for `sqlcomp`.
//!
//! This crate is the innermost Clean Architecture boundary. It must not depend on
//! any other `sqlcomp-*` crate.

use std::path::{Component, Path, PathBuf};

mod reporting;

pub use reporting::{
    Diagnostic, DiagnosticReport, DiagnosticResult, DiagnosticSeverity, SourceLocation,
    SourcePosition, SourceRange,
};

/// Header line that identifies files generated and managed by sqlcomp.
pub const GENERATED_FILE_HEADER: &str = "// @generated by sqlcomp. Do not edit.";

/// Validated project configuration accepted by application use cases.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectConfig {
    config_dir: PathBuf,
    source: SourceConfig,
    output: OutputConfig,
    database: DatabaseConfig,
    target: TargetConfig,
}

impl ProjectConfig {
    /// Build a validated project configuration from its sections.
    #[must_use]
    pub const fn new(
        config_dir: PathBuf,
        source: SourceConfig,
        output: OutputConfig,
        database: DatabaseConfig,
        target: TargetConfig,
    ) -> Self {
        Self {
            config_dir,
            source,
            output,
            database,
            target,
        }
    }

    /// Directory containing `sqlcomp.config.json`.
    #[must_use]
    pub fn config_dir(&self) -> &Path {
        &self.config_dir
    }

    /// Source file selection settings.
    #[must_use]
    pub const fn source(&self) -> &SourceConfig {
        &self.source
    }

    /// Generated output settings.
    #[must_use]
    pub const fn output(&self) -> &OutputConfig {
        &self.output
    }

    /// Database metadata settings.
    #[must_use]
    pub const fn database(&self) -> &DatabaseConfig {
        &self.database
    }

    /// Target-language settings.
    #[must_use]
    pub const fn target(&self) -> &TargetConfig {
        &self.target
    }
}

/// Source file selection settings from `sqlcomp.config.json`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SourceConfig {
    include: Vec<String>,
    exclude: Vec<String>,
}

impl SourceConfig {
    /// Build source file selection settings.
    #[must_use]
    pub const fn new(include: Vec<String>, exclude: Vec<String>) -> Self {
        Self { include, exclude }
    }

    /// Include glob patterns relative to the configuration file directory.
    #[must_use]
    pub fn include(&self) -> &[String] {
        &self.include
    }

    /// Exclude glob patterns relative to the configuration file directory.
    #[must_use]
    pub fn exclude(&self) -> &[String] {
        &self.exclude
    }
}

/// Generated output settings from `sqlcomp.config.json`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OutputConfig {
    dir: String,
}

impl OutputConfig {
    /// Build generated output settings.
    #[must_use]
    pub const fn new(dir: String) -> Self {
        Self { dir }
    }

    /// Output directory relative to the configuration file directory.
    #[must_use]
    pub fn dir(&self) -> &str {
        &self.dir
    }
}

/// Database metadata settings from `sqlcomp.config.json`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DatabaseConfig {
    dialect: DatabaseDialect,
    url_env: String,
}

impl DatabaseConfig {
    /// Build database metadata settings.
    #[must_use]
    pub const fn new(dialect: DatabaseDialect, url_env: String) -> Self {
        Self { dialect, url_env }
    }

    /// Configured database dialect.
    #[must_use]
    pub const fn dialect(&self) -> DatabaseDialect {
        self.dialect
    }

    /// Environment variable name that contains the database URL.
    #[must_use]
    pub fn url_env(&self) -> &str {
        &self.url_env
    }
}

/// Supported MVP database dialects.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DatabaseDialect {
    /// Official `MySQL` 8.x.
    MySql,
}

impl DatabaseDialect {
    /// Return the stable configuration spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::MySql => "mysql",
        }
    }
}

/// Target-language settings from `sqlcomp.config.json`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TargetConfig {
    language: TargetLanguage,
}

impl TargetConfig {
    /// Build target-language settings.
    #[must_use]
    pub const fn new(language: TargetLanguage) -> Self {
        Self { language }
    }

    /// Configured target language.
    #[must_use]
    pub const fn language(&self) -> TargetLanguage {
        self.language
    }
}

/// Supported MVP target languages.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TargetLanguage {
    /// `TypeScript` SQL builder generation.
    TypeScript,
}

impl TargetLanguage {
    /// Return the stable configuration spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::TypeScript => "typescript",
        }
    }
}

/// Resolved compilation work order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompilationPlan {
    config_dir: PathBuf,
    source_include: Vec<PathBuf>,
    source_exclude: Vec<PathBuf>,
    output_dir: PathBuf,
    database: DatabaseConfig,
    target: TargetConfig,
}

impl CompilationPlan {
    /// Build a resolved compilation plan.
    #[must_use]
    pub const fn new(
        config_dir: PathBuf,
        source_include: Vec<PathBuf>,
        source_exclude: Vec<PathBuf>,
        output_dir: PathBuf,
        database: DatabaseConfig,
        target: TargetConfig,
    ) -> Self {
        Self {
            config_dir,
            source_include,
            source_exclude,
            output_dir,
            database,
            target,
        }
    }

    /// Directory containing `sqlcomp.config.json`.
    #[must_use]
    pub fn config_dir(&self) -> &Path {
        &self.config_dir
    }

    /// Include glob patterns resolved relative to the configuration directory.
    #[must_use]
    pub fn source_include(&self) -> &[PathBuf] {
        &self.source_include
    }

    /// Exclude glob patterns resolved relative to the configuration directory.
    #[must_use]
    pub fn source_exclude(&self) -> &[PathBuf] {
        &self.source_exclude
    }

    /// Generated output directory resolved relative to the configuration directory.
    #[must_use]
    pub fn output_dir(&self) -> &Path {
        &self.output_dir
    }

    /// Database metadata settings for this compile run.
    #[must_use]
    pub const fn database(&self) -> &DatabaseConfig {
        &self.database
    }

    /// Target-language settings for this compile run.
    #[must_use]
    pub const fn target(&self) -> &TargetConfig {
        &self.target
    }

    /// Return a source path relative to the configuration directory.
    #[must_use]
    pub fn source_relative_path(&self, source_path: impl AsRef<Path>) -> Option<PathBuf> {
        let relative_path = source_path
            .as_ref()
            .strip_prefix(&self.config_dir)
            .ok()?
            .to_path_buf();

        is_safe_relative_path(&relative_path).then_some(relative_path)
    }
}

fn is_safe_relative_path(path: &Path) -> bool {
    path.components()
        .all(|component| matches!(component, Component::CurDir | Component::Normal(_)))
}

/// Query identifier exactly as written in source metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct QueryId(String);

impl QueryId {
    /// Build a query identifier.
    #[must_use]
    pub const fn new(value: String) -> Self {
        Self(value)
    }

    /// Query ID text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Metadata parsed from an MVP `type: query` annotation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct QueryMetadata {
    id: String,
    cardinality: Option<Cardinality>,
}

impl QueryMetadata {
    /// Build parsed query metadata.
    #[must_use]
    pub const fn new(id: String, cardinality: Option<Cardinality>) -> Self {
        Self { id, cardinality }
    }

    /// Query ID exactly as written in source metadata.
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Optional cardinality override from source metadata.
    #[must_use]
    pub const fn cardinality(&self) -> Option<Cardinality> {
        self.cardinality
    }
}

/// Raw query extracted from SQL source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RawQuery {
    metadata: QueryMetadata,
    sql: String,
    source_path: Option<PathBuf>,
    source_location: Option<SourceLocation>,
}

impl RawQuery {
    /// Build a raw query from parsed metadata and SQL text.
    #[must_use]
    pub const fn new(metadata: QueryMetadata, sql: String) -> Self {
        Self {
            metadata,
            sql,
            source_path: None,
            source_location: None,
        }
    }

    /// Attach the source SQL path relative to the configuration directory.
    #[must_use]
    pub fn with_source_path(mut self, path: impl Into<PathBuf>) -> Self {
        self.source_path = Some(path.into());
        self
    }

    /// Attach source location context for diagnostics.
    #[must_use]
    pub fn with_source_location(mut self, location: SourceLocation) -> Self {
        self.source_location = Some(location);
        self
    }

    /// Query metadata parsed from the source annotation.
    #[must_use]
    pub const fn metadata(&self) -> &QueryMetadata {
        &self.metadata
    }

    /// Raw SQL body for this query.
    #[must_use]
    pub fn sql(&self) -> &str {
        &self.sql
    }

    /// Source SQL path relative to the configuration directory, when known.
    #[must_use]
    pub fn source_path(&self) -> Option<&Path> {
        self.source_path.as_deref()
    }

    /// Optional source location for the SQL body.
    #[must_use]
    pub const fn source_location(&self) -> Option<&SourceLocation> {
        self.source_location.as_ref()
    }
}

/// Dialect analysis result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AnalyzedQuery {
    cardinality: Cardinality,
}

impl AnalyzedQuery {
    /// Build dialect analysis facts for a query.
    #[must_use]
    pub const fn new(cardinality: Cardinality) -> Self {
        Self { cardinality }
    }

    /// Cardinality inferred by dialect analysis.
    #[must_use]
    pub const fn cardinality(&self) -> Cardinality {
        self.cardinality
    }
}

/// Database metadata description normalized for compilation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DbQueryMetadata {
    columns: Vec<DbResultColumn>,
}

impl DbQueryMetadata {
    /// Build database query metadata.
    #[must_use]
    pub const fn new(columns: Vec<DbResultColumn>) -> Self {
        Self { columns }
    }

    /// Result columns described by the database metadata provider.
    #[must_use]
    pub fn columns(&self) -> &[DbResultColumn] {
        &self.columns
    }
}

/// Result column metadata from a database provider before final IR emission.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DbResultColumn {
    name: String,
    ty: CoreType,
    nullable: Option<bool>,
}

impl DbResultColumn {
    /// Build a database result column metadata value.
    #[must_use]
    pub const fn new(name: String, ty: CoreType, nullable: Option<bool>) -> Self {
        Self { name, ty, nullable }
    }

    /// Column name exactly as reported by the database metadata provider.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Language-neutral column type.
    #[must_use]
    pub const fn ty(&self) -> CoreType {
        self.ty
    }

    /// Database nullability metadata, when the provider can determine it.
    #[must_use]
    pub const fn nullable(&self) -> Option<bool> {
        self.nullable
    }

    /// Conservative nullability for generated output.
    #[must_use]
    pub fn is_nullable_for_output(&self) -> bool {
        self.nullable.unwrap_or(true)
    }

    /// Convert database metadata into a compiled result column.
    #[must_use]
    pub fn to_result_column(&self) -> ResultColumn {
        ResultColumn::new(self.name.clone(), self.ty, self.is_nullable_for_output())
    }
}

/// Language-neutral compiled query.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompiledQuery {
    id: QueryId,
    sql: String,
    cardinality: Cardinality,
    source_path: Option<PathBuf>,
    input: Vec<InputField>,
    row: Vec<ResultColumn>,
}

impl CompiledQuery {
    /// Build a compiled query Core IR value.
    #[must_use]
    pub const fn new(
        id: QueryId,
        sql: String,
        cardinality: Cardinality,
        input: Vec<InputField>,
        row: Vec<ResultColumn>,
    ) -> Self {
        Self {
            id,
            sql,
            cardinality,
            source_path: None,
            input,
            row,
        }
    }

    /// Attach the source SQL path relative to the configuration directory.
    #[must_use]
    pub fn with_source_path(mut self, path: impl Into<PathBuf>) -> Self {
        self.source_path = Some(path.into());
        self
    }

    /// Query ID exactly as written in source metadata.
    #[must_use]
    pub const fn id(&self) -> &QueryId {
        &self.id
    }

    /// SQL text for the compiled query.
    #[must_use]
    pub fn sql(&self) -> &str {
        &self.sql
    }

    /// Query result cardinality independent from any target-language syntax.
    #[must_use]
    pub const fn cardinality(&self) -> Cardinality {
        self.cardinality
    }

    /// Source SQL path relative to the configuration directory, when known.
    #[must_use]
    pub fn source_path(&self) -> Option<&Path> {
        self.source_path.as_deref()
    }

    /// Input fields for the query. MVP queries have an empty input list.
    #[must_use]
    pub fn input(&self) -> &[InputField] {
        &self.input
    }

    /// Result row columns for the query.
    #[must_use]
    pub fn row(&self) -> &[ResultColumn] {
        &self.row
    }
}

/// Query input field in Core IR.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct InputField {
    name: String,
    ty: CoreType,
    nullable: bool,
}

impl InputField {
    /// Build a query input field.
    #[must_use]
    pub const fn new(name: String, ty: CoreType, nullable: bool) -> Self {
        Self { name, ty, nullable }
    }

    /// Input field name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Language-neutral input type.
    #[must_use]
    pub const fn ty(&self) -> CoreType {
        self.ty
    }

    /// Whether the input field accepts null.
    #[must_use]
    pub const fn is_nullable(&self) -> bool {
        self.nullable
    }
}

/// Result row column in Core IR.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ResultColumn {
    name: String,
    ty: CoreType,
    nullable: bool,
}

impl ResultColumn {
    /// Build a result row column.
    #[must_use]
    pub const fn new(name: String, ty: CoreType, nullable: bool) -> Self {
        Self { name, ty, nullable }
    }

    /// Result column name exactly as reported by database metadata.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Language-neutral result column type.
    #[must_use]
    pub const fn ty(&self) -> CoreType {
        self.ty
    }

    /// Whether generated output should treat this column as nullable.
    #[must_use]
    pub const fn is_nullable(&self) -> bool {
        self.nullable
    }
}

/// Generated target-language file set.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFiles {
    files: Vec<GeneratedFile>,
}

impl GeneratedFiles {
    /// Build generated files.
    #[must_use]
    pub const fn new(files: Vec<GeneratedFile>) -> Self {
        Self { files }
    }

    /// Files produced by a target generator.
    #[must_use]
    pub fn files(&self) -> &[GeneratedFile] {
        &self.files
    }
}

/// One generated target-language file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedFile {
    path: PathBuf,
    contents: String,
}

impl GeneratedFile {
    /// Build a generated file.
    #[must_use]
    pub const fn new(path: PathBuf, contents: String) -> Self {
        Self { path, contents }
    }

    /// Generated file path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Generated file contents.
    #[must_use]
    pub fn contents(&self) -> &str {
        &self.contents
    }
}

/// Query cardinality in generated output.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Cardinality {
    /// A query returns zero or one row.
    One,
    /// A query returns zero or more rows.
    Many,
}

/// Language-neutral type classification for generated output.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CoreType {
    /// Boolean value.
    Bool,
    /// 32-bit integer value.
    Int32,
    /// 64-bit integer value.
    Int64,
    /// 64-bit floating-point value.
    Float64,
    /// Decimal value.
    Decimal,
    /// Text value.
    String,
    /// Binary value.
    Bytes,
    /// Date value.
    Date,
    /// Time value.
    Time,
    /// Date-time value.
    DateTime,
    /// JSON value.
    Json,
    /// Unknown database type.
    Unknown,
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use super::{
        AnalyzedQuery, Cardinality, CompilationPlan, CompiledQuery, CoreType, DatabaseConfig,
        DatabaseDialect, DbQueryMetadata, DbResultColumn, QueryId, QueryMetadata, RawQuery,
        ResultColumn, SourceLocation, SourcePosition, SourceRange, TargetConfig, TargetLanguage,
    };

    #[test]
    fn source_relative_path_returns_config_relative_path() {
        let config_dir = PathBuf::from("/tmp/sqlcomp-project");
        let plan = compilation_plan(config_dir.clone());

        let relative_path = plan
            .source_relative_path(config_dir.join("sql/users/list.sql"))
            .expect("source path should be inside config dir");

        assert_eq!(relative_path, Path::new("sql/users/list.sql"));
    }

    #[test]
    fn source_relative_path_rejects_parent_dir_after_config_prefix() {
        let config_dir = PathBuf::from("/tmp/sqlcomp-project");
        let plan = compilation_plan(config_dir.clone());

        assert_eq!(
            plan.source_relative_path(config_dir.join("../shared/users.sql")),
            None
        );
    }

    #[test]
    fn raw_query_preserves_metadata_sql_source_path_and_optional_source_location() {
        let location = SourceLocation::at_range(
            "sql/users.sql",
            SourceRange::point(
                SourcePosition::one_based(8, 1).expect("test position should be valid"),
            ),
        );
        let query = RawQuery::new(
            QueryMetadata::new("listUsers".to_owned(), Some(Cardinality::One)),
            "SELECT id FROM users;".to_owned(),
        )
        .with_source_path("sql/users.sql")
        .with_source_location(location.clone());

        assert_eq!(query.metadata().id(), "listUsers");
        assert_eq!(query.metadata().cardinality(), Some(Cardinality::One));
        assert_eq!(query.sql(), "SELECT id FROM users;");
        assert_eq!(query.source_path(), Some(Path::new("sql/users.sql")));
        assert_eq!(query.source_location(), Some(&location));
    }

    #[test]
    fn analyzed_query_exposes_inferred_cardinality() {
        let analysis = AnalyzedQuery::new(Cardinality::Many);

        assert_eq!(analysis.cardinality(), Cardinality::Many);
    }

    #[test]
    fn db_query_metadata_preserves_result_column_metadata() {
        let columns = vec![
            DbResultColumn::new("userId".to_owned(), CoreType::Int64, Some(false)),
            DbResultColumn::new("nickname".to_owned(), CoreType::String, Some(true)),
        ];
        let metadata = DbQueryMetadata::new(columns.clone());

        assert_eq!(metadata.columns(), columns);
    }

    #[test]
    fn compiled_query_represents_empty_mvp_input_and_result_columns() {
        let query = CompiledQuery::new(
            QueryId::new("listUsers".to_owned()),
            "SELECT id, name FROM users;".to_owned(),
            Cardinality::Many,
            Vec::new(),
            vec![
                ResultColumn::new("id".to_owned(), CoreType::Int64, false),
                ResultColumn::new("name".to_owned(), CoreType::String, true),
            ],
        );

        assert_eq!(query.id().as_str(), "listUsers");
        assert_eq!(query.sql(), "SELECT id, name FROM users;");
        assert_eq!(query.cardinality(), Cardinality::Many);
        assert_eq!(query.source_path(), None);
        assert!(query.input().is_empty());
        assert_eq!(query.row().len(), 2);
        assert_eq!(query.row()[0].name(), "id");
        assert_eq!(query.row()[0].ty(), CoreType::Int64);
        assert!(!query.row()[0].is_nullable());
        assert_eq!(query.row()[1].name(), "name");
        assert_eq!(query.row()[1].ty(), CoreType::String);
        assert!(query.row()[1].is_nullable());
    }

    #[test]
    fn compiled_query_preserves_source_path_when_available() {
        let query = CompiledQuery::new(
            QueryId::new("listUsers".to_owned()),
            "SELECT id FROM users;".to_owned(),
            Cardinality::Many,
            Vec::new(),
            Vec::new(),
        )
        .with_source_path("sql/users.sql");

        assert_eq!(query.source_path(), Some(Path::new("sql/users.sql")));
    }

    #[test]
    fn database_metadata_conservatively_treats_unknown_nullability_as_nullable() {
        let metadata = DbQueryMetadata::new(vec![DbResultColumn::new(
            "mystery".to_owned(),
            CoreType::Unknown,
            None,
        )]);
        let column = metadata.columns()[0].to_result_column();

        assert_eq!(column.name(), "mystery");
        assert_eq!(column.ty(), CoreType::Unknown);
        assert!(column.is_nullable());
    }

    fn compilation_plan(config_dir: PathBuf) -> CompilationPlan {
        CompilationPlan::new(
            config_dir,
            vec![PathBuf::from("sql/**/*.sql")],
            Vec::new(),
            PathBuf::from("src/generated/sqlcomp"),
            DatabaseConfig::new(DatabaseDialect::MySql, "DATABASE_URL".to_owned()),
            TargetConfig::new(TargetLanguage::TypeScript),
        )
    }
}
