name: "[format] Check (Reusable Workflow)"

on:
  workflow_call:
    inputs:
      dprint-version:
        description: dprint CLI version used by CI.
        required: false
        type: string
        default: 0.54.0

permissions:
  contents: read

jobs:
  dprint:
    name: dprint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup dprint
        uses: ./.github/actions/setup-dprint
        with:
          version: ${{ inputs.dprint-version }}

      - name: Check formatting
        run: dprint check
